### ISSUE TITLE
SnapFuzz is not working properly

### ISSUE THREAD

**Issue by songxpu** [srg-imperial/SnapFuzz-artefact#1]
Hi! This work is very rewarding.

After successfully building the file in accordance with the README, I found that SnapFuzz did not work properly and would hang during the initialization phase, as shown in the image below, which I suspect is related to Sabre, as the original AFLNET did not have this problem.

![image](https://user-images.githubusercontent.com/44093631/233615107-57bf0d81-c21a-4275-9456-5928adec0c00.png)

![image](https://user-images.githubusercontent.com/44093631/233614681-b7d2c70b-0526-4046-a876-171af8fb5e3e.png)

I had this problem on different Ubuntu 20.04 machines, even when I went to build SnapFuzz alone.

I am very confused as I lack knowledge of binary rewriting and would very much appreciate your help.

**Comment by andronat** [comment]
Hey @songxpu! Thanks for taking a look at SaBRe! Sorry for the hiccups! Usually problem rises when sabre can't communicate with the server you want to fuzz.

I see you invoke the fuzzing commands manually instead of using my automation scripts. There might be some important flags missing?

Because I'll be quite busy for the next couple of weeks due to traveling for work, may I ask you to try the process through my streamlined scripts and check if everything works?

If everything fails, I'll put some time asap to check for you.

**Comment by songxpu** [comment]
Thanks very much for your response!
It was a brilliant job and I am actually writing an email to you in case you didn't see this one issue.  : )

Firstly, I also tried using the script you provided and the result was the same, in fact I called the above command manually and it came from the output of the script so there should be no missing flags, such as the image below.

![image](https://user-images.githubusercontent.com/44093631/233617412-10fa4e27-6d3f-4880-8da4-77545c395a82.png)

Then, after running for ten minutes we saw that the output directory of fuzzer was still the initial seed, which, combined with the manual invocation of the command, probably did get stuck because of some primitive.

![image](https://user-images.githubusercontent.com/44093631/233618359-5ac29472-602c-4493-89ab-60beb218b522.png)

Incidentally, I tested and found it very strange that all 5 programs encounter this problem.

Finally, thank you again for your reply and I hope you can help check it out when you have time.

**Environment**
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

**Comment by songxpu** [comment]
Hi @andronat, I may have found the root of the problem. 

After some debugging, I found it interesting that the SaBRe provided by SnapFuzz can't seem to find the ld with the debug information as follows.

```bash
~/SnapFuzz-artefact/builds/sabre/build$ ./sabre ./plugins/sbr-trace/libsbr-trace.so -- /bin/ld
# output
sabre: ~/SnapFuzz-artefact/builds/sabre/loader/rewriter.c:562: find_ld_symbol: Assertion `false && "We couldn't find ld symbols"' failed.
```
However, if I use the latest branch of SaBRe, the result is normal and the result is as follows (Everything is fine):

![image](https://user-images.githubusercontent.com/44093631/233637582-6a7ff516-736d-4277-b317-fb915472c61a.png)

Therefore, I suspect that the initial cause is that the version of SaBRe provided by SnapFuzz cannot find the ld, causing the aflnet to get stuck. as it mentioned that one asserts failed in sabre/loader/rewriter.c:562.

Then I used the latest branch of SaBRe to replace the version given in the build and everything worked fine (**except ftp, and shows timeout**).

So I personally recommend updating SaBRe in build.sh, but it doesn't work for FTP experimentation. I found through debug that afl-fuzz can already communicate with fftp program and does send and receive packets, but afl-fuzz will still time out, which is very strange.

It's not clear if SaBRe caused the problem because the original AFLNET did not have this problem.

---
Update:

For ftp, I can set a larger timeout and successfully solve the timeout problem, but this may not be correct as the performance is terrible, probably similar to the original AFLNET, and too far removed from the boost described in the paper.

**Comment by songxpu** [comment]
I have successfully solved all the problems and made some foolish mistakes. I would like to summarize the above issues.

- Firstly, replacing SnapFuzzy with the latest branch of SaBRe can solve the first problem 
- Secondly, it is best to use script for testing, as this can solve the problem of poor FTP performance.

Wishing you all the best in your work in the coming weeks !

**Comment by tuftjd** [comment]
@songxpu How to use the latest branch of SaBRe, in particular, how to replace SnapFuzzy with the latest branch of SaBRe
